labhunter/cart/urls.py
from django.urls import re_path
from .views import *


urlpatterns = [
    re_path(r'^$', cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<file_id>\d+)/$', cart_add, name='cart_add'),
    re_path(r'^remove/(?P<file_id>\d+)/$', cart_remove, name='cart_remove'),
]

labhunter/labhunter/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.template.defaulttags import url
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'^orders/', include(('service.urls', 'orders'), namespace='orders')),
    re_path(r'paypal/', include('paypal.standard.ipn.urls')),
    path('', include('service.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labhunter/service/urls.py
from django.urls import path, re_path, include
from .views import *

urlpatterns = [
    path('', ServiceHome.as_view(), name='home'),
    #path('upload/', upload, name='upload'),
    path('file/<slug:file_slug>/', select_file, name='select-file'),
    path('addWork/', AddWork.as_view(), name='add-work'),
    path('category/<slug:cat_slug>/', ShowCat.as_view(), name='select-cat'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logoutuser, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    re_path(r'^create/$', order_create, name='order-create'),
    #path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    #path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
]

labhunter/cart/models.py
from django.db import models

# Create your models here.

labhunter/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]


class CartAddProductForm(forms.Form):
    #quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

labhunter/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from service.utils import menu
from .cart import Cart
from .forms import CartAddProductForm
from service.models import *


@require_POST
def cart_add(request, file_id):
    cart = Cart(request)
    file = get_object_or_404(Files, id=file_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(file=file,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, file_id):
    cart = Cart(request)
    file = get_object_or_404(Files, id=file_id)
    cart.remove(file)
    return redirect('cart:cart_detail')




def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    login_menu = menu.copy()
    if not request.user.is_authenticated:
        login_menu.pop(1)
    context = {
        'menu': login_menu,
        'categories': categories,
        'cart': cart,
        'title': 'Корзина',
        'previous_url': request.META.get('HTTP_REFERER'),

    }
    return render(request, 'cart/detail.html', context=context)

labhunter/cart/templates/cart/detail.html
{% extends "service/base.html" %}
{% load static %}
    {{title}}
{% block content %}
<div class="cart_wrapper">
    <h1>Ваша корзина покупок</h1>
    {% if cart|length > 0 %}
        <table class="cart cart-detail">
            <thead>
            <tr>
                <th>Фото</th>
                <th>Продукт</th>
                <th>Кількість</th>
                <th>Ціна</th>
                <th>Видалити</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
            {% with file=item.file %}
            <tr>
                <td>
                    <a href="{{ file.get_absolute_url }}">
                        <img src="
                                    {% if file.photo %}
                                        {{ file.photo.url }}
                                    {% endif %}" height="100" width="100">
                    </a>
                </td>
                <td>{{ file.title }}</td>
                <td>{{ item.quantity }}</td>
                <td class="num">{{ item.total_price }}₴</td>
                <td><a class="remove" href="{% url 'cart:cart_remove' file.id %}"><button class="delete-item">X</button></a></td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Загальна вартість</td>
                <td colspan="3"></td>
                <td class="num">{{ cart.get_total_price }}₴</td>
            </tr>
            </tbody>
        </table>
        <p class="text-right">
            <button class="cart-btn continue-shopping"><a class="button light" href="{{ previous_url }}">Continue
                shopping</a></button>
            <button class="cart-btn checkout"><a href="{% url 'orders:order-create' %}" class="button">Checkout</a>
            </button>
        </p>
    {% else %}
        <h2>Корзина порожня :(</h2>
    {% endif %}
</div>
{% endblock %}