labhunter/cart/urls.py
from django.urls import re_path
from .views import *


urlpatterns = [
    re_path(r'^$', cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<file_id>\d+)/$', cart_add, name='cart_add'),
    re_path(r'^remove/(?P<file_id>\d+)/$', cart_remove, name='cart_remove'),
]

labhunter/labhunter/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.template.defaulttags import url
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'^orders/', include(('service.urls', 'orders'), namespace='orders')),
    re_path(r'paypal/', include('paypal.standard.ipn.urls')),
    path('', include('service.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labhunter/service/urls.py
from django.urls import path, re_path, include
from .views import *

urlpatterns = [
    path('', ServiceHome.as_view(), name='home'),
    #path('upload/', upload, name='upload'),
    path('file/<slug:file_slug>/', select_file, name='select-file'),
    path('addWork/', AddWork.as_view(), name='add-work'),
    path('category/<slug:cat_slug>/', ShowCat.as_view(), name='select-cat'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logoutuser, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    re_path(r'^create/$', order_create, name='order-create'),
    #path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    #path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
]

labhunter/service/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy


class Files(models.Model):
    title = models.CharField(max_length=255, verbose_name='Назва файлу')
    teacher = models.CharField(max_length=255, verbose_name='Викладач')
    docx = models.FileField(upload_to='files/docx/', verbose_name='Шлях до документу')
    topic = models.CharField(max_length=255, null=True, verbose_name='Тема роботи')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', null=True, verbose_name='Титулка')
    work_number = models.IntegerField(null=True, blank=True, verbose_name='Номер роботи')
    other_files = models.FileField(upload_to='files/other/', blank=True, verbose_name='Дадаткові файли')
    file_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    google_docx = models.URLField(max_length=200, null=True, unique=True, blank=True, verbose_name='Посилання на файл')
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, verbose_name='Ціна')
    discount_price = models.FloatField(blank=True, null=True)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категорія')
    sub = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Предмет')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('select-file', kwargs={'file_slug': self.file_slug})
#
   # def get_add_to_cart_url(self):
   #     return reverse("service:add-to-cart", kwargs={
   #         "pk": self.pk
   #     })
#
   # def get_remove_from_cart_url(self):
   #     return reverse("service:remove-from-cart", kwargs={
   #         "pk": self.pk
   #     })

    class Meta:
        verbose_name = 'Усі файли'
        verbose_name_plural = 'Усі файли'


class Category(models.Model):
    cat_name = models.CharField(max_length=100, db_index=True, verbose_name='Категорія')
    cat_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.cat_name

    def get_absolute_url(self):
        return reverse('select-cat', kwargs={'cat_slug': self.cat_slug})

    class Meta:
        verbose_name = 'Категорії'
        verbose_name_plural = 'Категорії'


class Subject(models.Model):
    sub_name = models.CharField(max_length=255, db_index=True, verbose_name='Назва предмету')
    course = models.IntegerField(verbose_name='Курс')
    semester = models.IntegerField(verbose_name='Семестр')
    sub_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.sub_name

    class Meta:
        verbose_name = 'Предмети'
        verbose_name_plural = 'Предмети'


class Order(models.Model):
    first_name = models.CharField(max_length=50, null=True, verbose_name="Ім'я")
    last_name = models.CharField(max_length=50, null=True, verbose_name='Фамілія')
    email = models.EmailField(null=True, unique=True, verbose_name='Електронна пошта')
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')
    ordered_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False, verbose_name='Оплата')

    class Meta:
        ordering = ('-start_date',)
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, related_name='items', verbose_name='Замовлення')
    file = models.ForeignKey(Files, on_delete=models.CASCADE, null=True, related_name='order_items', verbose_name='Файл')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, verbose_name='Ціна')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Кількість')

    class Meta:
        verbose_name = 'Файли'
        verbose_name_plural = 'Файли'

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

labhunter/service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import *


class AddFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категорія не вибрана"
        self.fields['sub'].empty_label = "Предмет не вибраний"

    class Meta:
        model = Files
        fields = ['title', 'teacher', 'file_slug', 'docx', 'topic', 'photo', 'work_number', 'other_files', 'cat', 'sub']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'})
        }


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор паролю', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email']

labhunter/service/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, ListView, DetailView
from django.contrib import messages
from django.utils import timezone

from cart import cart
from cart.cart import Cart
from cart.forms import CartAddProductForm
from .forms import *
from .models import *
from .utils import *

from .tasks import order_created
# biletskyi_labhunter

#menu = [
#    {'title': "Про сайт", 'url_name': 'about'},
#    {'title': "Завантажити роботу", 'url_name': 'add-work'},
#    {'title': "Зворотній зв'язок", 'url_name': 'contact'},
#        ]
#categories = [
#    {'title': "Лабораторні", 'url_name': 'lab'},
#    {'title': "Курсові", 'url_name': 'curs'},
#    {'title': "ДЗ", 'url_name': 'dz'},
#    {'title': "РГР", 'url_name': 'rgr'},
#]


#def upload(request):
#    context = {}
#    if request.method == "POST":
#        uploaded_file = request.FILES['document']
#        fs = FileSystemStorage()
#        name = fs.save(uploaded_file.name, uploaded_file)
#        context['url'] = fs.url(name)
#    return render(request, 'service/upload.html', context)



class ServiceHome(DataMixin, ListView):
    model = Files
    template_name = 'service/home.html'
    context_object_name = 'files'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Головна сторінка')
        return dict(list(context.items()) + list(c_def.items()))


#def home(request):
#    files = Files.objects.all()
#    categories = Category.objects.all()
#
#    context = {
#        'files': files,
#        'menu': menu,
#        'categories': categories,
#        'cat_selected': 0,
#        'title': 'Головна сторінка',
#    }
#    return render(request, 'service/home.html', context=context)
#class ShowFile(DataMixin, DetailView):
#    model = Files
#    template_name = 'service/file.html'
#    slug_url_kwarg = 'file_slug'
#    context_object_name = 'file'
#
#    def get_context_data(self, *, object_list=None, **kwargs):
#        context = super().get_context_data(**kwargs)
#        c_def = self.get_user_context(title='categories')
#        return dict(list(context.items()) + list(c_def.items()))

def about(request):
    return HttpResponse('Про сайт')

class ShowCat(DataMixin, ListView):
    model = Files
    template_name = 'service/home.html'
    context_object_name = 'files'
    allow_empty = False
    def get_queryset(self):
        return Files.objects.filter(cat__cat_slug=self.kwargs['cat_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Категорія - ' + str(context['files'][0].cat), cat_selected=str(context['files'][0].cat))
        return dict(list(context.items()) + list(c_def.items()))

#def select_cat(request, cat_slug):
#    files = Files.objects.filter(cat__cat_slug=cat_slug)
#    categories = Category.objects.all()
#
#    if len(files) == 0:
#        raise Http404()
#
#    context = {
#        'files': files,
#        'categories': categories,
#        'menu': menu,
#        'title': 'Вибір по рубрикам',
#        'cat_selected': cat_slug,
#    }
#    return render(request, 'service/home.html', context=context)


def select_file(request, file_slug):
    file = get_object_or_404(Files, file_slug=file_slug)
    categories = Category.objects.all()
    cart_file_form = CartAddProductForm()
    login_menu = menu.copy()
    shop_cart = cart.Cart(request)
    all_file = set()
    for fd in Files.objects.all():
        all_file.add(fd.id)
    for sc in shop_cart:
        if sc['file'].id in all_file:
            all_file.remove(sc['file'].id)
        else:
            pass
    if not request.user.is_authenticated:
        login_menu.pop(1)
    context = {
        'file': file,
        'menu': login_menu,
        'title': file.title,
        'categories': categories,
        'cat_selected': file.cat_id,
        'cart_file_form': cart_file_form,
        'shop_cart': shop_cart,
        'all_file': all_file,
    }

    return render(request, 'service/file.html', context=context)


def contact(request):
    return HttpResponse("Зворотній зв'язок")


#def login(request):
#    if request.method == 'POST':
#        form = Test(request.POST)
#        if form.is_valid():
#            print((form.cleaned_data.get('title') == "Міша"))
#    else:
#        form = Test()
#    return render(request, 'service/login.html', {'form': form})


class AddWork(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddFileForm
    template_name = 'service/upload.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Завантаження роботи')
        return dict(list(context.items()) + list(c_def.items()))

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'service/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Реєстрація')
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'service/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизація')
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logoutuser(request):
    logout(request)
    return redirect('login')


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         file=item['file'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            order_created.delay(order.id)
            return render(request, 'service/created.html',
                          {'order': order, 'title': 'Thank you', })
    else:
        form = OrderCreateForm
    categories = Category.objects.all()
    login_menu = menu.copy()
    if not request.user.is_authenticated:
        login_menu.pop(1)
    context = {
        'cart': cart,
        'form': form,
        'title': 'Замовлення',
        'menu': login_menu,
        'categories': categories,
    }
    return render(request, 'service/create.html', context=context)

labhunter/service/templates/service/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="data:;base64,=">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'service/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'service/css/register.css' %}">
    <link rel="stylesheet" href="{% static 'service/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'service/css/create.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css"
          integrity="sha384-eoTu3+HydHRBIjnCVwsFyCpUDZHZSFKEJD0mc3ZqSBSb6YhZzRHeiomAUWCstIWo" crossorigin="anonymous">
</head>
<body>
{% block header %}
<nav class="header">
    <input type="checkbox" name="menu" id="btn-menu"/>
    <label for="btn-menu">Головне меню</label>
    <ul class="header__section">
        <li class="header__item headerLogo"><a href="{% url 'home' %}"><i class="bi bi-house-fill"></i></a></li>
        {% for m in menu %}
        <li class="header__item headerButton"><a href="{% url m.url_name %}">{{ m.title }}</a></li>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <li class="header__item headerButton right push"><a href="{% url 'logout' %}">Вийти</a></li>
        {% if cart|length > 0 %}
        <li class="header__item headerButton right">
            <button class="bi-cart3-btn" data-count="{{ cart|length }}"><a href="{% url 'cart:cart_detail' %}"><i
                    class="bi bi-cart3 bi-2xl"></i></a></button>
        </li>
        {% else %}
        <li class="header__item headerButton right"><a href="{% url 'cart:cart_detail' %}"><i
                class="bi bi-cart3 bi-2xl"></i></a></li>
        {% endif %}
        {% else %}
        <li class="header__item headerButton right push"><a href="{% url 'login' %}">Вхід</a></li>
        {% if cart|length > 0 %}
        <li class="header__item headerButton right">
            <button class="bi-cart3-btn" data-count="{{ cart|length }}"><a href="{% url 'cart:cart_detail' %}"><i
                    class="bi bi-cart3 bi-2xl"></i></a></button>
        </li>
        {% else %}
        <li class="header__item headerButton right"><a href="{% url 'cart:cart_detail' %}"><i
                class="bi bi-cart3 bi-2xl"></i></a></li>
        {% endif %}
        {% endif %}
    </ul>
</nav>

{% endblock header %}
<!-- menu -->
<div class="wrapper">
    <div class="dropdown-menu">
        <div class="sidebar">
            {% if cat_selected == 0 and request.path == '/' %}
            <h2>Категорії</h2>
            {% else %}
            <h2><a href="{% url 'home' %}">Категорії</a></h2>
            {% endif %}
            <ul class="dropdown">
                {% for cat in categories %}
                {% if cat.cat_name == cat_selected %}
                <li>
                    <div class="select-cat no-selected"><i class="bi bi-check2"></i> {{cat.cat_name}}</div>
                </li>
                {% else %}
                <li>
                    <div class="select-cat"><a href="{{ cat.get_absolute_url }}"><i class="bi bi-diamond"></i>
                        {{cat.cat_name}} </a></div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            <div class="social_media dropdown">
                <a href="#"><i class="bi bi-instagram"></i></a>
                <a href="#"><i class="bi bi-telegram"></i></a>
            </div>
        </div>
    </div>
    <div class="main_content">
        <!-- Кінець menu -->
        <div class="header-content">
            <ul class="content-box user__name">
                {% if request.user.is_authenticated %}
                <li class="user__name right">Користувач - {{ user.username }}</li>
                {% else %}
                <li class="content-title">Welcome new user</li>
                {% endif %}
            </ul>

            <div class="cart">
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                Ваша корзина:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ cart.get_total_price }}₴
                </a>
                {% else %}
                Ваша корзина пуста.
                {% endif %}
                {% endwith %}
            </div>
        </div>
        <div class="info">
            <!-- Блок контента -->
            {% block content %}
            {% endblock %}
            <!-- Конец блока контента -->
        </div>
    </div>
    <div class="main_filter">
        <div class="header-filter"></div>
    </div>
</div>
<script src="{% static 'service/js/script.js' %}"></script>
</body>
</html>

labhunter/service/templates/service/create.html
{% extends "service/base.html" %}

{% block content %}

<div class="order-box">
    <div class="order-label">
        <div class="order-info">
            <h2>Замовлення</h2>

            <form action="." method="post" class="order-form">

                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>

                {% for f in form %}
                    <div class="user-box">
                        <p>{{ f }}<label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label></p>
                    </div>
                        <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <button type="submit">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Зробити замовлення
                </button>
            </form>
        </div>
        <div class="order-detail">
            <h3>Деталі замовлення</h3>
            <ul>
                {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.file.title }}
                    <span>{{ item.total_price }}$</span>
                </li>
                {% endfor %}
            </ul>
            <p class="total">Загальна вартість: {{ cart.get_total_price }}$</p>
        </div>
        <div class="order-third"></div>
    </div>
</div>
{% endblock %}

labhunter/service/templates/service/created.html
{% extends "service/base.html" %}

{{title}}

{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

labhunter/service/templates/service/file.html
{% extends 'service/base.html' %}

{% block content %}

<div class="file-box">
    {% if file.photo %}

    <div class="box-1">
        <p>
            <iframe class="iframe_file" src='{{file.docx}}' width='820' height='600' frameborder='0'></iframe>
        </p>
    </div>
    {% endif %}
    <div class="box-2">
        <h3>{{file.title}}</h3>
        <p class="price">Ціна: {{ file.price }}₴</p>

        {% if file.id in all_file %}
        <form class="form-add_to_cart" action="{% url 'cart:cart_add' file.id %}" method="post">
            {{ cart_file_form }}
            {% csrf_token %}
            <button type="submit">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Додати до кошику
            </button>
        </form>
        {% else %}
        <h3><button class="btn-cart_detail"><a class="file-cart_detail" href="{% url 'cart:cart_detail' %}">Робота уже в корзині</a></button></h3>
    </div>
    {% endif %}
</div>
{% endblock %}

labhunter/service/templates/service/home.html
{% extends 'service/base.html' %}

{% block content %}

<div class="content">
    <ul class="list-articles">
        {% for f in files %}
        <li class="file">
            <div class="article-panel">
                <p class="first">Категорія: {{f.cat}}</p>
                {% if f.sub %}
                    <p class="subject">Предмет: {{f.sub}}</p>
                {% else %}
                    <p class="subject">Предмет: ---</p>
                {% endif %}
                {% autoescape on %}
                    <div class="item"><a href="{{ f.get_absolute_url }}">
                        {% if f.photo %}
                            <img src="{{ f.photo.url }}" height="100%" width="100%">
                        {% endif %}
                    </a>
                    </div>
                {% endautoescape %}
                {% if f.id in all_file %}
                    <form action="{% url 'cart:cart_add' f.id %}" method="post">
                        {% csrf_token %}
                            <button type="submit" class="button-buy-lab">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                Купити
                            </button>
                    </form>
                {% else %}
                    <div class="button-buy-lab"><a href="{% url 'cart:cart_detail' %}">Додано в корзину</a></div>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

labhunter/service/templates/service/login.html
{% extends 'service/base.html' %}

{% block content %}
<div class="login-box">
    <h2>{{ title }}</h2>

    <form class="login-form" method="post">

        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
        <div class="user-box">
            <p>{{ f }}<label class="form-label" for="{{ f.id_for_label }}">{{f.label}}</label></p>
        </div>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <div class="register"><a href="{% url 'register' %}">Зареєструватись</a></div>
        <button type="submit">
             <span></span>
             <span></span>
             <span></span>
             <span></span>
             Увійти
        </button>
    </form>
</div>
{% endblock %}

labhunter/service/templates/service/register.html
{% extends 'service/base.html' %}

{% block content %}
<div class="register-label">
    <h2>{{ title }}</h2>

    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <div class="register-box">
            <p>{{ f }}<label class="form-label" for="{{ f.id_for_label }}">{{f.label}} </label></p>
        </div>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Зареєструватись
        </button>
    </form>
</div>
{% endblock %}

labhunter/service/templates/service/upload.html
{% extends 'service/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="{% url 'add-work' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit">Добавити</button>
    </form>

{% endblock %}